# library(readxl)
# dat <- read_excel("D:/sample-xlsx-file-for-testing.xlsx")
# View(dat)
# nrow(dat)
# head(dat)
# attach(dat)
# # model1 <- lm(Profit ~ SalePrice)
# # summary(model1)
# # plot(SalePrice, Profit, main = "Plot")
# # abline(model1, col = "red", lwd = 3)
# # anova(model1)
# model2 <- lm(Profit ~ SalePrice + UnitsSold + ManufacturingPrice)
# # abline(model2, col = "red", lwd = 3)
# # anova(model2)
# summary(model2)
# plot(SalePrice, Profit, main = "Plot")
# barplot(Profit, main = "BarPlot of Profit")
# hist(Profit, main = "BarPlot of Price")
# boxplot(Profit, main = "BoxPlot")
# par(mfrow = c(2, 2))